export default {
  login: "usard",
  id: 132735347,
  node_id: "U_kgDOB-lhcw",
  avatar_url: "https://avatars.githubusercontent.com/u/132735347?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/usard",
  html_url: "https://github.com/usard",
  followers_url: "https://api.github.com/users/usard/followers",
  following_url: "https://api.github.com/users/usard/following{/other_user}",
  gists_url: "https://api.github.com/users/usard/gists{/gist_id}",
  starred_url: "https://api.github.com/users/usard/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/usard/subscriptions",
  organizations_url: "https://api.github.com/users/usard/orgs",
  repos_url: "https://api.github.com/users/usard/repos",
  events_url: "https://api.github.com/users/usard/events{/privacy}",
  received_events_url: "https://api.github.com/users/usard/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 5,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2023-05-06T05:43:46Z",
  updated_at: "2023-09-17T00:09:29Z",
};

// export default {
//   login: "john-smilga",
//   id: 42133389,
//   node_id: "MDQ6VXNlcjQyMTMzMzg5",
//   avatar_url: "https://avatars3.githubusercontent.com/u/42133389?v=4",
//   gravatar_id: "",
//   url: "https://api.github.com/users/john-smilga",
//   html_url: "https://github.com/john-smilga",
//   followers_url: "https://api.github.com/users/john-smilga/followers",
//   following_url:
//     "https://api.github.com/users/john-smilga/following{/other_user}",
//   gists_url: "https://api.github.com/users/john-smilga/gists{/gist_id}",
//   starred_url:
//     "https://api.github.com/users/john-smilga/starred{/owner}{/repo}",
//   subscriptions_url: "https://api.github.com/users/john-smilga/subscriptions",
//   organizations_url: "https://api.github.com/users/john-smilga/orgs",
//   repos_url: "https://api.github.com/users/john-smilga/repos",
//   events_url: "https://api.github.com/users/john-smilga/events{/privacy}",
//   received_events_url:
//     "https://api.github.com/users/john-smilga/received_events",
//   type: "User",
//   site_admin: false,
//   name: "John Smilga",
//   company: "Coding Addict",
//   blog: "www.johnsmilga.com",
//   location: "Los Angeles",
//   email: null,
//   hireable: null,
//   bio: "Creator of Coding Addict",
//   twitter_username: "john_smilga",
//   public_repos: 152,
//   public_gists: 0,
//   followers: 1495,
//   following: 0,
//   created_at: "2018-08-06T06:48:23Z",
//   updated_at: "2020-07-08T05:01:32Z",
// };
